### ISSUE TITLE
Map he/she/they to any in API v1

### ISSUE THREAD

**Issue by ghost** [cyyynthia/pronoundb.org#100]
Not sure if you're still accepting change proposals to the API v1 compatibility layer or if you'd rather just leave it as is, but if someone has he/him, she/her and they/them pronouns set (in any order), it may be better to map them to "any" rather than just the first set of pronouns.

**Comment by cyyynthia** [comment]
I'm not fundamentally against changes to the compatibility algorithm for v1, but I have some strong doubts I'll modify it this way. Any compared to the he/she/they trio has imho a different meaning as it potentially includes neos, and eventually it (although I would recommend against using it on someone who doesn't explicitly say it's fine due to its past use as hateful).

The rational for truncating to only the first two sets was based on the assumption in most cases the order of pronouns specify an order of preference. While it doesn't carry the same meaning as the trio, my belief is that any doesn't either and in fact looses precision people might expect.

Right now I'm not particularly interested in changing the behavior of v1 for this matter. That being said, if more voices share the view that any would be a better fit, then I might consider. I can't ignore a large portion of PDB traffic is still v1 and will likely remain v1 for a while, so I do care about having a decent v1 compatibility so long the API remains operating, and especially in the early days of v2 release.

**Comment by ghost** [comment]
Yeah true, it's not a perfect mapping, though I think most people who use "any pronouns" generally mean he/she/they. Some may be fine with it/its and/or neopronouns too.

**Comment by cyyynthia** [comment]
Adding an additional detail : the way v2 pronouns are represented in their short form (which only include 2 sets) also behave this way (although it generally have a way to show the expanded form with all 3 sets, which APIv1 lacks)

Having the APIv1 behavior match (roughly) the way PronounDB represents short form of 3 sets makes the result a bit more predictable : people already saw the pronouns may be represented this way. It is not accurate for when `any` or `ask` is included, but is close enough.

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/7a97e4ee-2197-4759-9203-72d160016286)

**Comment by cyyynthia** [comment]
I'll be closing this issue, as API v1 is getting closer to being discontinued and I don't think it's worth to work on that for just a few months left of service

/cc @alexiayaa
