### ISSUE TITLE
Twitter isn't working

### ISSUE THREAD

**Issue by vUbev** [cyyynthia/pronoundb.org#106]
I was surprised today to see a twitter user's pronouns. However when going to the site and trying to link my account, i was encountered with [this message](https://imgur.com/a/hWiHdIB)
oh, and, when trying to log in to twitch (the only available website back when i got the extension) it said my account didn't exist? I just made a new one, but thought that was odd since I've been using it forever.

**Comment by cyyynthia** [comment]
Hey there, I think there is no issues here but some misunderstandings. Let me help to clarify:

 - Regarding the message, PronounDB is a "third-party app", in the sense that it is not managed or operated by Twitter. This message should show up at the bottom of the page for everyone who uses a "Login via Twitter" feature. If the login is simply not working, try on a desktop; Twitter since the weird fat guy has been getting more and more broken, it wouldn't surprise me this is simply broken on Twitter's end.

 - PronounDB have had support for 4 platforms the day of its release. You might have encountered the other "Twitch chat pronouns" extension, which is way more popular but exclusively works on Twitch - this is probably where you set your pronouns initially.

**Comment by vUbev** [comment]
This was on a desktop. I guess it's just broken on their end.
And you were right! It was the other add-on. Odd, because it's been working with this extension, even though I never set my own pronouns until now with it.

**Comment by cyyynthia** [comment]
The PronounDB extension doesn't fetch pronouns from other sources than pronoundb.org, it was probably some other extension (e.g. FFZ which IIRC has integration with the other extension), or the other extension itself.

As for the Twitter login, I checked again and it works fine for me. I double checked with my alt account to confirm it's not working "just for me" due to me being the owner of the Twitter 3rd party app (and you can clearly see how broken this looks, especially the footnote "Made by . Read undefined's (...)" 🤣 

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/262000a9-5472-4625-843a-7ae97da18d94)
