### ISSUE TITLE
[Suggestions] New PronounDB Features

### ISSUE THREAD

**Issue by tobezdev** [cyyynthia/pronoundb.org#114]
Just a few quick ideas I thought of completely randomly. Felt like a waste to not share them.
Happy to cook up some concepts to show you guys if you wish. :)
Thanks!

`Custom Pronoun Support:`
Allow users to input their own custom pronouns, ensuring inclusivity for all gender identities.

`Educational Resources:`
Incorporate educational materials about gender identity and pronouns to help users understand the importance of using correct pronouns and fostering inclusivity.

`Pronoun Usage Statistics:
Offer users insights into their pronoun usage over time, highlighting trends and promoting awareness of language habits.

`Pronoun Pronunciation Guide:`
Provide audio recordings or phonetic spellings for pronouns to assist users in pronouncing them correctly. This could be especially helpful in conjunction with the Custom Pronoun Support.

**Comment by cyyynthia** [comment]
- This is already mentioned in the readme as to why this will not be a thing
- This one kind of exists with the Pronouns 101 page, and I think pronouns.page does a very great job of having tons of resources I think linking to them is the best thing to do here
- I thought about it, but I currently don't keep track of historical data and one thing I'm afraid of is the user count being too small and stats being able to be usable to infer data about people in particular which is something I'd rather like to avoid if possible
- Why not, though once again pronouns.page does a very good job already so I'm not sure

**Comment by tobezdev** [comment]
Makes sense, happy to have a go at them via a pull request if that's something you want to see,
Also just realised that PronounDB uses black text for websites, even when they are on dark mode so might fix that in the pull.

![Dark Mode Text Preview](https://github.com/cyyynthia/pronoundb.org/assets/83095177/73bca17c-35f0-4ea9-965f-2fd6a59a4e71)

**Comment by busybox11** [comment]
@TobezDev I just made a pull request to fix this on Twitter (haven't noticed it on other websites though): https://github.com/cyyynthia/pronoundb.org/pull/115

**Comment by cyyynthia** [comment]
> Also just realised that PronounDB uses black text for websites, even when they are on dark mode so might fix that in the pull.

Version 0.14.2 is being rolled out with Twitter injection fixed (finally...)

As for the other points, I'm unsure what to do with this issue (see my previous remarks) 🤷🏻‍♀️

**Comment by cyyynthia** [comment]
Well as this issue is overly broad in scope I'll just close it. For the reference:
- Custom pronouns support will not be added, as mentioned in the README
- I'm not against having some educational resources. There's the "Pronouns 101" page which I wrote a while ago to help people who just got introduced to the concept of pronouns but nothing more. I'm not against extending the `/wiki/` section of the website, but I personally don't have the time to maintain such thing. I will take the time to review PR adding such things if they come up. Feel free to open a new issue for this point specifically.
- While I am myself a fan of graphs, I am dealing with sensitive data and have a responsibility to be careful with what I do with it. Some sets (like `it/its`, or neos whenever they finally get added to the site) are very low usage which is a problem, as it makes it possible to infer data about individuals specifically as the aggregation doesn't mix enough data together.
- Unsure. It may have some uses, but considering there will not be custom pronouns I'm unsure how useful that would be. Maybe with neos, but then again I think handing this type of things off to pronouns.page is a better alternative as they have a much more mature dataset.
