### ISSUE TITLE
Green Dot Appears under Extension Icon on All Unsupported Websites

### ISSUE THREAD

**Issue by Avakining** [cyyynthia/pronoundb.org#121]
On every unsupported website, the screenshotted below 'notification' dot appears under the extension overflow icon and the extension icon itself. From what I remember, this happened with the latest update.

Firefox 125.0.3
pronoundb 0.14.4

<img width="44" alt="Screenshot 2024-05-02 at 14 15 38" src="https://github.com/cyyynthia/pronoundb.org/assets/25210618/d53439dc-dcdc-4133-875c-8b1b172ecbbd">
<img width="350" alt="Screenshot 2024-05-02 at 14 15 55" src="https://github.com/cyyynthia/pronoundb.org/assets/25210618/30cf3946-b51a-4690-836a-3804ab891a5a">

**Comment by Avakining** [comment]
This is, obviously, very low priority. It just annoys me a tiny bit every time it happens

**Comment by cyyynthia** [comment]
In the last update I enabled MV3 builds on Firefox, but it seems there are still bugs on there :/

https://bugzilla.mozilla.org/show_bug.cgi?id=1851083

Besides rolling back to MV2 that seems to be outside of my control :(

**Comment by Zardoz89** [comment]
I agree, it's pretty annoying for me and some people.

**Comment by cyyynthia** [comment]
I totally understand the frustration and I will rollback the extension to MV2 format as a workaround hopefully this week, at worst next week.

The root cause is an issue in Firefox as mentioned above reported 8 months ago... As I don't use Firefox primarily I didn't notice that; I only test the extension loads and works as expected and nothing more - and based on the compatibility data I had I thought upgrading (and getting rid of annoying build hacks to output both flavors of Manifest) was okay :(

I'm sorry this is happening, fix will arrive soon 🤞🏻

**Comment by cyyynthia** [comment]
Version 0.14.5 is out and should no longer suffer from this problem. 🎉

**Comment by Avakining** [comment]
The bug in Firefox is fixed in FF 129 (which will enter public beta soon -- probably in the next few days -- and release in the next month or two)

**Comment by Avakining** [comment]
Firefox 129 is now out, which fixes this bug
