### ISSUE TITLE
Support for the Twitch Chat Pronouns extension?

### ISSUE THREAD

**Issue by SammyForReal** [cyyynthia/pronoundb.org#123]
Hello!
I really love this extension and prefer it over other solutions.

On Twitch, many use the [Twitch Chat Pronouns](https://pr.alejo.io/) extension however.
My question now is: Would it be in the scope of this project to integrate their database into this extension as well?

Because otherwise I need to disable one to only use another _(or keep both enabled which then tends to two pronouns at the same time however, which is not nice either)_

**Comment by cyyynthia** [comment]
Well, given the API differences and the fact this is a Twitch-specific thing, this would require quite a lot of additional code to get it to work, including how the extension handles incoming messages from Twitch - which is really not something I want to deal with (nor have the motivation to do, there's a lot of things I want to ship in the extension that I haven't got around already).

The easiest solution is to use both and load a bit of extra CSS using your extension of choice. Or, instead of CSS you can also do it using uBO if that's your thing.
 
- CSS
  - PronounDB first: `.chat-line__message:has(.pronoundb-chat-badge-wrapper) .pr-badge-wrapper { display: none !important; }`
  - Twitch Chat Pronouns first: `.chat-line__message:has(.pr-badge-wrapper) .pronoundb-chat-badge-wrapper { display: none !important; }`
- uBO
  - PronounDB first: `twitch.tv##.chat-line__message:has(.pronoundb-chat-badge-wrapper) .pr-badge-wrapper`
  - Twitch Chat Pronouns first: `twitch.tv##.chat-line__message:has(.pr-badge-wrapper) .pronoundb-chat-badge-wrapper`

**Only use a single one**, there's no point in combining. Mentioning these all so it can be used as a reference for anyone looking for the same information 😺

**Comment by SammyForReal** [comment]
Thank you for the detailed answer! That's really helpful. 😄

I will close this issue now.
