### ISSUE TITLE
Facebook support

### ISSUE THREAD

**Issue by ayukovt** [cyyynthia/pronoundb.org#15]
Is facebook support planned for the extension? I use facebook a lot since everyone in my country uses it so it would be really cool to have that app support facebook

**Comment by cyyynthia** [comment]
I spent some time investigating this issue, and I'm currently facing some rather problematic issues:

The Facebook API never returns the real user IDs to the applications, instead they return an "App-Scoped User ID" which is unique to my application (and that cannot be later used by the extension, which will see the real User IDs. It seems there are no way of turning a real user ID to an App-Scoped one, which is where the problem resides.

Most of what I could find about that problem seem to be hacks Facebook doesn't like and patches, so I don't know if I'll be able to pull a proper way of doing it. I'll keep looking for a viable way, and hope to find one.

Worst case I can use the extension as a client-side companion and scrape the ID myself - but that's a solution I'd prefer to avoid since it adds quite a lot of complexity to both the backend and the extension.

**Comment by cyyynthia** [comment]
Good news, the OAuth flow is complete and working 🎉

What remains to do is the extension module for Facebook, which will be responsible for adding pronouns where they should be.

**Comment by cyyynthia** [comment]
I finished the Facebook integration, and it will be available when version 0.5.0 of the extension is out, which I'll publish in the coming days.

Due to the Chrome Web Store being veeery slow with its review process (version 0.4.0 isn't even available yet..), it might take a week or more before it's available there, Microsoft Edge takes 2-3 business days to review, and Firefox is just a few minutes. I'll close this issue once the extension will be available on the 3 stores.

**Comment by cyyynthia** [comment]
0.5.0 is on its way to your web browser 🎉

It's already available on Firefox, and pending review on Microsoft Edge Addons and the Chrome Web Store, I'll close this issue once it's been released on those two as well.

**Comment by ayukovt** [comment]
Hey! I'm happy you were able to make it work with Facebook! I'll definitely pass that extension to some of my friends that could definitely use it :)

**Comment by cyyynthia** [comment]
Version 0.5.0 is now up on all 3 extension stores 🎉
