### ISSUE TITLE
Pronouns are added on newly loaded messages on Discord

### ISSUE THREAD

**Issue by busybox11** [cyyynthia/pronoundb.org#17]
This is kinda hard to explain but i'll do my best.

When you're opening a conversation, the pronouns are not there.
They're being added only when you're scrolling through unloaded messages or sending new ones.

I hope you understood what I mean and that you'll be able to fix this 👍

**Comment by cyyynthia** [comment]
CNR, mind sharing a recording of what you're trying to report, as well as sharing your environment?

**Comment by busybox11** [comment]
Sorry, I fotgot to check GitHub this week.
Sure, I'll do it when I'll be back to my home.

**Comment by busybox11** [comment]
Uhh, yeah, I did not really think about that in the past two weeks.
Is it okay for you tho?

**Comment by cyyynthia** [comment]
I tried to address this issue in b0183b743993ae746e0f6ba02c658452b0bb2fdd, however since I couldn't reproduce locally I don't know if this change will be enough.

Version 0.3.0 of the extension (which includes the fix) is currently pending review in the Chrome Web Store, which is a process that can either be done in 30 seconds or a few days. Keep an eye on the extension see when you get the update, and let me know if this still occurs.
