### ISSUE TITLE
Adding support for osu!

### ISSUE THREAD

**Issue by Synaelle** [cyyynthia/pronoundb.org#20]
It would be great to add support for osu! (the website)
There is a lot of missgender happening. That would be great to have the pronouns on the profile & the forum

**Comment by ayukovt** [comment]
not trying to be rude or smth but I wouldn't find any use for it in osu community cuz it's toxic af (sure, some people would probably actually use it but that's not most of them)

**Comment by Synaelle** [comment]
You can't say that it's not useful on osu! because the community is cancer, the extension is on discord & twitter and here the community is way worse. And why toxic people will even use this? I mean they don't care. If cyyynthia doesn't want to implement this I'm fine with that choice, since it's just a proposition, but don't say it's about the toxicity of the community.

**Comment by cyyynthia** [comment]
The purpose of this extension is not to make toxic people suddenly become wholesome: it's not because an extension that tells pronouns exists that everyone will suddenly become friendly and use the proper pronouns for everyone. The extension is more designed so you can start a conversation online with someone and know how to call them right away.

The only reasons I'd be against working on an integration is if there are too many technical difficulties (no way of externally authenticating someone through OAuth for example), or if there are little to no social interactions and an integration would essentially be worthless (e.g. a platform where you never get to interact or see details about any other member).

I will be making an osu! integration, and it's already listed as coming soon here https://pronoundb.org/supported.
