### ISSUE TITLE
Options for 3+ pronouns to be shown

### ISSUE THREAD

**Issue by viiuan** [cyyynthia/pronoundb.org#26]
If possible, it would be nice for this kind of option, as someone who goes by 3 pronoun sets (she, he, and it).
I do know the Ask and Other options are a thing, but all the sets I use are there, just not able to be shown together, which feels funky.

**Comment by cyyynthia** [comment]
Looking back at this issue, the problem is that in many places it isn't possible UX-wise to show more than 2 pronoun sets (and even then it already gets quite bulky, as for example in Twitch chats).

I will get to implement this at some point, but the extension will most likely only show 2 sets in many "inline" places (Twitch chats, Twitter tweets, Discord messages, ...), and will only show all 3 pronouns in profiles and popouts.

**Comment by cyyynthia** [comment]
I've been doing work on the upcoming APIv2 update, and a lot of information about it (including gotchas about certain sets) can be found at #68 

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/bf2fb162-cb34-431f-aff8-7717d4a71fa7)

Notes and gotchas:
 - As you can see on the screenshot, short representation only includes 2 sets
 - Certain sets (currently: "any", "ask", or "other") are considered "final" sets, and you cannot pick a set after these

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/2e414d91-258e-4bf6-a96c-cc197e6ccd6f)

This is not available yet, but it's getting closer!

**Comment by cyyynthia** [comment]
This is now possible! You can set a 3rd set on the website now, and the update to the extension adding support for the 3rd set is out. 🎉
