### ISSUE TITLE
Add support for a userscript

### ISSUE THREAD

**Issue by fluteds** [cyyynthia/pronoundb.org#27]
An idea more than an issue but it would be lovely if this was available as a userscript. It ideally would be another download method, if at all possible to build alongside the browser extensions of course! Then there's more support for other browsers other than Chrome, Firefox and Edge.

**Comment by cyyynthia** [comment]
After closer inspection, there is a major problem to accomplish this which is Content Security Policy. Because the extension fetches data from the API at pronoundb.org, if websites have strict CSP policies (which they should!), the request will be unable to succeed as a userscript, as the browser will reject it.

The extension bypasses such restrictions as they run independently of the webpage context and have privileged access to some APIs, which is not something feasible as a general-purpose userscript.

Sure, not all websites have a CSP policy in place but it's definitely something they should be doing and that they might start doing at any time (and that, as I said, should be doing). Right now, out of the 5 services currently supported, only Twitch has no CSP set which means the userscript would only work on Twitch. It's something I guess...

So considering that, plus the need for me to add either tons of `if`s everywhere or to write a 2nd codebase for it, it's not something I'll be working on.
