### ISSUE TITLE
Neopronouns

### ISSUE THREAD

**Issue by randomzigzag** [cyyynthia/pronoundb.org#3]
Made this issue for people to discuss the topic; whether or not neopronouns should be added, and how they should be implemented if they are.

**Comment by rosegayming** [comment]
I can't find a good list at the moment but I think just adding the more popular/common ones as well as a button on the site to open a new pr or issue to request new ones. If there's a lot of requests, maybe make a separate repo so the main one doesn't get cluttered.

**Comment by cyyynthia** [comment]
The main issue with neopronouns is that there are a REALLY large amount of them, and I feel like building up a list of all of them is near impossible and the list will miss some for sure. It would also require some UX improvements on the pronoun selector since the list would get really large, and finding the one you want may be complicated.

Letting people input their pronouns doesn't sound like a good approach, especially since on the backend side only a short identifier is kept (and it would allow easy abuse by evil people to mock communities, and I honestly cba to go and moderate everything).

I at least added the ability for people to set their pronouns to "Other". While it can be used as a fallback, it kind of defeats the purpose of the project so I'm unsure if this is viable either.

> If there's a lot of requests, maybe make a separate repo so the main one doesn't get cluttered.

I'd rather keep everything in a single repo, rather than having multiple satellite repositories.

**Comment by randomzigzag** [comment]
I think adding the popular/common ones and keeping a fallback "Other" option is good.

**Comment by rosegayming** [comment]
@cyyynthia I think this is a good list https://lgbta.wikia.org/wiki/Neopronouns. Don't think that many would clutter list.

**Comment by cyyynthia** [comment]
If pronoundb starts supporting some neopronouns and not others, it'd be more than legitimate for people going by unlisted neopronouns to ask for them to be added to our list, and the "yeah but it's not popular enough" answer will definitely look harsh to some and is unfair to me. But then, we go back to accepting all requests and cluttering the list.

There's also the problem of determining the "popular/common" side of things. pronoundb.org is a website regulated by the French law, its operations and decisions must comply with the French law, which severely restricts how data about gender identity may be used (article L.226-19 of the penal code). It is therefore really complicated to use and justify the "popularity" argument, since building up statistical data is basically illegal.

**Comment by rosegayming** [comment]
If anyone wants to read it, [French Penal Code (Article 226-19 on pg. 56)](https://www.legal-tools.org/doc/418004/pdf/).
It seems that the only good options are a custom text box (which will probably get abused and require moderation), or rename "Other" to "Other (Ask Me)" or something similar.

**Comment by randomzigzag** [comment]
"Other (Ask Me)" seems like a viable solution to me. I don't think moderating a custom text box for this would be worth anybody's time.

**Comment by cyyynthia** [comment]
> I don't think moderating a custom text box for this would be worth anybody's time.

As I said earlier I really don't want to start having to take too much time time in moderating platform's usage, and a customizable text box is an easy path for hostile people to mock people, which is something I want to avoid.

> "Other (Ask Me)" seems like a viable solution to me.

I will add that as an option below "Other", and summarize this discussion in the README or somewhere, for people wondering about neopronouns support.

**Comment by rosegayming** [comment]
The ideal scenario would be a team moderating a fully custom text box but I highly doubt anyone would be willing to moderate it constantly or even some of the time.

**Comment by cyyynthia** [comment]
If the platform grows enough and if there's enough demand I may reconsider the decisions here, but I clearly don't have the time to put in moderating nor do I want to get moderators and spend time building moderation tools (which takes time that I still don't have) (although I'm doing some really basic admin tools, but they're too basic for such purpose).

**Comment by deingithub** [comment]
Hi! I learnt about this tool today from a friend on Discord and would like to suggest a few improvements regarding neopronouns:
- Make the pronoun input a regular text input with an attached [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) for more input options that don't clutter the UI. For ~ extra compatibility ~, you could even have a separate, regular `<select>` box that gets hidden by JS on page load if the user has a browser that supports datalist (practically everything except Opera Mobile 3)
- Either allow completely custom input *or* add a suggestion box and a minimal-friction (think: less than two minutes' work) way for you to add new pronouns. You're unlikely to be at a scale where adding pronouns would be a full-time job.
- If you decide to allow completely custom input, implement a minimal slur filter, possibly as simple as a linebreak-separated file of regexes that a prospective pronoun has to not match any of, in order to be considered acceptable. If you get reports for abuse (implement a tool for this or provide contact details to make it informal), just add a new regex for that case. Don't commit the regexes to the repo, and trolls will run out of time eventually. Add a possibility for people to locally hide pronouns (ideally, with one click, imagine a small [:x:] showing up next to a pronoun added by this) to be persisted in the next best equivalent of localStorage you can get a hold of depending on the platform.
- Drop the frankly atrocious excuse from the README. You are already telling me my pronouns aren't popular enough, politely informing me that you feel a little bad about doing so doesn't help.

I'd be delighted to expand on any of these points and offer clarification or help if necessary.

**Comment by rosegayming** [comment]
I assume the reason she doesn't want to add a custom input is because, someone can and will eventually bypass any filter/check and she's too busy with university to moderate it.  As well, she's not saying your pronouns aren't popular enough, she's saying she explicitly *doesn't want* to do that.

**Comment by cyyynthia** [comment]
> Make the pronoun input a regular text input with an attached <datalist>

That was one of my ideas, although it'd be a bit annoying to map the input text to the actual identifier the backend expects, await for a supported value to send to the backend, display errors, ... but this is not a big issue and just implementation-side, so nothing to worry too much about.

> Either allow completely custom input or add a suggestion box and a minimal-friction

I didn't commit & push it at the time you commented (although mentioned), but I won't add support for completely custom input, for the reasons I mentioned on the readme. As of suggestions, there's already an extremely powerful tool created by GitHub Inc. called "the issue tracker" :p, so if I can avoid having to write and maintain more code than necessary, I will (I'll elaborate on this in a bit).

> Drop the frankly atrocious excuse from the README.

The point I made there is that *if* we only support a subset of neo-pronouns based on their popularity/usage, *then* we will have to say this to some people. This is as factual as it gets, and I'm not telling anything to anyone (that's actually the whole point of not going down this route). Factual information is not something I will drop, because it's facts and I'm, as far as I'm aware, still allowed to state facts.

I'll assume this was an unfortunate misunderstanding of what I said which can happen. However I'll point out that I find quite inappropriate to add up "little", to throw me under the bus even further. I try my best to keep things friendly for everyone while also satisfying my time constrains, so this kind of treatment in return makes me wonder whether it was a good idea or not to make this project. But anyway I will stop commenting on this here, there's no point in fighting over it. I just wanted to point that out.

-----

Neo-pronouns are overall a sensitive topic and no matter what will be done, no solution will be perfect. The amount of existing neo-pronouns makes keeping a list a huge pain when you're out of the loop, and there's no way for me to ensure proper moderation and troll filtering because of this. In the end, I just want to avoid them because, as this thread shows, they are a constant source of discussions, subjective views and (for some implementations) a vector of personal attacks. I have way too many things to care about already in my personal and professional life to reliably allocate time to pronoundb.org. I mostly designed the platform as something I can get running and let run on its own, with absolutely 0 need for moderation, little to no maintenance work, and with a structure which allows adding without effort OAuth providers, and modules to the extension so I don't need to spend hours on new features.

The current way pronoundb.org work allows for the platform to operate this way, since there's absolutely no ways to abuse the platform when you can only pick from a predefined set. Each module, once the abstractions and utils were done, took no longer than an hour or two to get done. This is great for me since it means I can work on it on an afternoon and get something done, without having to wonder if I'll be able to get back to it the next day to finish on what I started, or if I start something that'll reach completion maybe in the next decade.

Adding pronouns means having to push a backend update and roll out an update to all 3 stores (which is not as easy as clicking a button, all stores perform reviews which take time and make publishing frequent updates not ideal). The only thing I'm considering is having admin endpoints to block some accounts, which I don't even know if I'll end up needing or implementing them.

**Comment by sylv256** [comment]
> > Make the pronoun input a regular text input with an attached
> 
> That was one of my ideas, although it'd be a bit annoying to map the input text to the actual identifier the backend expects, await for a supported value to send to the backend, display errors, ... but this is not a big issue and just implementation-side, so nothing to worry too much about.
> 
> > Either allow completely custom input or add a suggestion box and a minimal-friction
> 
> I didn't commit & push it at the time you commented (although mentioned), but I won't add support for completely custom input, for the reasons I mentioned on the readme. As of suggestions, there's already an extremely powerful tool created by GitHub Inc. called "the issue tracker" :p, so if I can avoid having to write and maintain more code than necessary, I will (I'll elaborate on this in a bit).
> 
> > Drop the frankly atrocious excuse from the README.
> 
> The point I made there is that _if_ we only support a subset of neo-pronouns based on their popularity/usage, _then_ we will have to say this to some people. This is as factual as it gets, and I'm not telling anything to anyone (that's actually the whole point of not going down this route). Factual information is not something I will drop, because it's facts and I'm, as far as I'm aware, still allowed to state facts.
> 
> I'll assume this was an unfortunate misunderstanding of what I said which can happen. However I'll point out that I find quite inappropriate to add up "little", to throw me under the bus even further. I try my best to keep things friendly for everyone while also satisfying my time constrains, so this kind of treatment in return makes me wonder whether it was a good idea or not to make this project. But anyway I will stop commenting on this here, there's no point in fighting over it. I just wanted to point that out.
> 
> Neo-pronouns are overall a sensitive topic and no matter what will be done, no solution will be perfect. The amount of existing neo-pronouns makes keeping a list a huge pain when you're out of the loop, and there's no way for me to ensure proper moderation and troll filtering because of this. In the end, I just want to avoid them because, as this thread shows, they are a constant source of discussions, subjective views and (for some implementations) a vector of personal attacks. I have way too many things to care about already in my personal and professional life to reliably allocate time to pronoundb.org. I mostly designed the platform as something I can get running and let run on its own, with absolutely 0 need for moderation, little to no maintenance work, and with a structure which allows adding without effort OAuth providers, and modules to the extension so I don't need to spend hours on new features.
> 
> The current way pronoundb.org work allows for the platform to operate this way, since there's absolutely no ways to abuse the platform when you can only pick from a predefined set. Each module, once the abstractions and utils were done, took no longer than an hour or two to get done. This is great for me since it means I can work on it on an afternoon and get something done, without having to wonder if I'll be able to get back to it the next day to finish on what I started, or if I start something that'll reach completion maybe in the next decade.
> 
> Adding pronouns means having to push a backend update and roll out an update to all 3 stores (which is not as easy as clicking a button, all stores perform reviews which take time and make publishing frequent updates not ideal). The only thing I'm considering is having admin endpoints to block some accounts, which I don't even know if I'll end up needing or implementing them.

Not adding Neopronouns defeats the purpose of PronounDB. You're basically telling everyone who uses them "fuck you."

**Comment by Toby222** [comment]
It's a technical limitation, not a choice.
And you can circumvent it by using "Other pronouns" or "Ask me my pronouns"

**Comment by cyyynthia** [comment]
It should be noted that the README has been updated a few days ago (commit e0510b53) reflecting a change in this decision. It would have been a good idea to give this oddly named file a look beforehand...

**Comment by NinekoTheCat** [comment]
https://github.com/liquidnya/pronouns-chat/issues/2#issuecomment-2798124846
this is another example of a user not wanting to switch to pronounsdb as primary because of lack of neopronouns
