### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by pixelcmtd** [cyyynthia/pronoundb.org#33]
You already support Chrome and FF, why not Safari? [Packaging Web Extensions for Safari](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) looks pretty trivial to me.

**Comment by cyyynthia** [comment]
While Chrome has an entry fee of $5 and Firefox has no entry fee to publish in their stores, in order to officially distribute an extension for Safari you must be part of the Apple Developer Program which costs ~$100 per year.

As I am not willing to pay that much to publish a single extension through official means offered by Apple, I will keep targeting only the 3 stores I originally had interest in publishing in (Chrome, Firefox and Edge), unless there is enough demand to get the extension to another store where publishing doesn't cost me that much money.

**Comment by pixelcmtd** [comment]
You know that there are other ways to distribute software than the App Store?

**Comment by BenSegal855** [comment]
> unless there is enough demand to get the extension to another store where publishing doesn't cost me that much money.

**Comment by cyyynthia** [comment]
My comment was clear on the "official means", if I put the effort into packaging the extension for Safari it's to distribute it through these means. Apple's officially documented way of deploying web extensions is through the App Store.

Not to mention the requirement of Xcode to pack the extension which is also a blocker for me and makes a Safari build from me even less likely.

**Comment by j-f1** [comment]
Would you accept a PR to add an Xcode project for the Safari extension? Then, interested people (like me) would be able to build it ourselves. No changes are required to the current extension code (beyond the addition of new files in the Xcode project directory).

**Comment by cyyynthia** [comment]
I have mixed feelings about it. Having code that is bound to be unmaintained by me and which can go out of date at any given time without appropriated care doesn't align with my quality standards - especially with large scale changes bound to happen in 2022 (Manifest v3 migration). The lack of testing on the Safari build also throws me off a bit.

To me, anything in the repository is considered "officially supported" which simply wouldn't be the case here (and I myself have PronounDB related projects that are not part of the repo because not "official" despite being by the original author, me).

I'm not against having community builds (provided license compliance, which isn't too hard with a permissive license), and I think you can probably spin something with git submodules to review the impact of upstream changes on Safari build (which is probably one of the "best" solutions).
