### ISSUE TITLE
Pronouns are not appering in twitter profile just in the profile preview popup

### ISSUE THREAD

**Issue by SIGTERM-015** [cyyynthia/pronoundb.org#34]
![image](https://user-images.githubusercontent.com/70113068/133856723-da02e08a-bbf8-466e-a822-06e898bf3d68.png)
![image](https://user-images.githubusercontent.com/70113068/133856729-307a32f3-837d-4534-af2f-daa25bb972f4.png)

**Comment by cyyynthia** [comment]
This has been fixed in the ongoing rewrite as of commit 65403c0976376fd67200ad1f94ae080233e33d60, with additional places where pronouns are shown by the extension. There is no ETA for this rewrite to land in browser extension stores, unfortunately. I'll close the issue once the update has been released.

![image](https://user-images.githubusercontent.com/9999055/141347508-e192f19c-6ce2-4887-954a-2e96ea0f9059.png)

**Comment by cyyynthia** [comment]
The extension update has started to roll out! Version 0.6.0 is now available on Firefox, and should be available on Edge and Chrome in the following days.

**Comment by SIGTERM-015** [comment]
Can I download the extension directly from the repository?

**Comment by cyyynthia** [comment]
I don't provide the built extension directly in the repository (at least yet, maybe I will in the future once I get GitHub Actions stuff going on). You can however build the extension from source yourself, provided you have NodeJS and pnpm installed.

**Comment by cyyynthia** [comment]
Version 0.6.1 is now available in all extension stores! 🎉
