### ISSUE TITLE
Load Custom Modules

### ISSUE THREAD

**Issue by HerXayah** [cyyynthia/pronoundb.org#5]
Make it like PreMid to load own JS Files to test it out :D

This would make it easier since compiling always is annoying

**Comment by cyyynthia** [comment]
I won't implement something to load modules on-fly since it'd just add unnecessary code to maintain and work with. The build command (which isn't available on the repo yet) is a single command which generates an unpacked extension that can be loaded in Chrome easily. No need to make a custom module loader.
