### ISSUE TITLE
Remove GitHub

### ISSUE THREAD

**Issue by TheKodeToad** [cyyynthia/pronoundb.org#90]
https://github.blog/changelog/2023-03-01-add-pronouns-to-your-github-profile/

idk how finished this feature is... however you should already be able to see it in action!

**Comment by cyyynthia** [comment]
Hey there, it's not that simple.

While GitHub now has a native picker, the GitHub.com website is not the only place where pronouns are fetched, and some platforms like Modrinth have a module pulling pronouns using the PDB API for GitHub users.

GitHub's API tends to be very limited when it comes to fetching information without an access token, and even then it becomes quickly problematic to fetch data for arbitrary users. That being said, some Modrinth members shown some enthusiasm when the integration module came around, so they may built on top of it and fetch this extra bit of information for display on their website. In the meantime, there's no urge to do anything.

Another thing, while I only ever mentioned it in #68 without too much details, I do plan to add some new features to PronounDB (instead of "just" being a basic key-value store for pronouns), which will still make an integration relevant. 

For the foreseeable future, GitHub authentication and the GitHub extension module will remain available and maintained. I might in a future update align PronounDB's injection to what GitHub decided to do with their design, but again there's no urge to do anything.

**Comment by TheKodeToad** [comment]
It defintely looks weird having the pronouns twice tbh, but this can be tweaked i suppose. Thanks!

**Comment by cyyynthia** [comment]
Yeah, this is what I meant in my last sentence. I'll align the injection with what GitHub did for consistency, and avoid duplicates.

For instance, I myself have different things set on PronounDB vs what I set in bios or native fields; I only have the it/its secondary set mentioned on PDB. Some other people who are in a complicated situation around these topics may also take advantage of the fact what's set on PDB is only seen by PDB users, which are more likely to be supportive of it than the average Twitter user.

I've seen PDB used in many different ways, and I've seen it help some people get started one step at a time, and I'm very happy to see PDB used this way. Some things I have at the back of my mind are more "precise" pronouns indications, such as specifying whether compounds set (e.g. she/it) mean indifferent, prefer she, or "please use a bit of both". I also thought of some features such as randomizing the set shown (for people falling under the "use a bit of both", or fluid people). etc, etc.

Plus some features beyond just pronouns... There's a handful of things I wish to implement but time constrains make it a bit tough, haha. One day!

**Comment by TheKodeToad** [comment]
I was just reiterating on what you said kind of. Sorry if it was confusing!

**Comment by ghost** [comment]
Yeah, having PronounDB override the native pronouns field sounds like a good idea.

It's worth noting that the native pronouns field doesn't currently seem to be visible to logged out users.
